name: CI/CD

on:
  push:
    branches:
      - main
    # tags:
    ## `any` branch by default
    # branches: []

jobs:
  # 1.0 - Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: 'yarn'
      - run: yarn --immutable
      - run: yarn build:website

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./packages/websites/.output/

  # 2.0 - Deployment
  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: website
          path: website

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Generate release name
        id: release_name
        run: echo "release_name=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Deploy with Rsync
        run: |
          rsync -avz -e ssh website ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:www/alexisbesson/releases/${{ env.release_name }}/

      - name: Change current release version
        uses: appleboy/ssh-action@master
        env:
          RELEASE_NAME: ${{ env.release_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: RELEASE_NAME
          script: |
            cd www/alexisbesson
            ln -snf "releases/$RELEASE_NAME" current
